model:
  dim: 384
  freqs_per_bands: !!python/tuple
  - 7
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
  - 7
  - 7
  - 7
  - 9
  - 9
  - 9
  - 10
  - 10
  - 11
  - 13
  - 13
  - 13
  - 15
  - 16
  - 17
  - 19
  - 20
  - 20
  - 22
  - 24
  - 26
  - 28
  - 29
  - 31
  - 33
  - 36
  - 39
  - 41
  - 44
  - 47
  - 50
  - 54
  - 57
  - 61
  - 66
  - 71
  - 76
  - 80
  - 86
  - 93
  - 99
  - 105
  - 113
  - 122
  - 130
  mask_estimator_depth: 3
  num_stems: 1
  stft_hop_length: 441
  stft_n_fft: 2048
training:
  target_instrument: other
